In [1]:
# pip install geopy geopandas shapely

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
import prepare_data

In [40]:
data = prepare_data.open_and_clean_all(
    "data/raw/clalit/parallel",
    "data/raw/maccabi/maccabi_full_data_with_appointments.json",
)

In [41]:
data.to_csv("data/clean/merged.csv", index=False)
data[data["kupah"] == "maccabi"].to_csv("data/clean/maccabi.csv", index=False)
data[data["kupah"] == "clalit"].to_csv("data/clean/clalit.csv", index=False)

In [42]:
data

,timestamp,available_date,kupah,profession,doctor_name,address,days_diff,city
0,2026-07-30 16:51:12.000000,2026-08-02 00:00:00,clalit,אורתופדיה,"ד""ר לוין מארק","שיאון, קצרין",3.0,קצרין
1,2026-07-30 16:51:12.000000,2026-08-02 00:00:00,clalit,אורתופדיה,"ד""ר מחאמיד חסן",מעלה עירון,3.0,מעלה עירון
2,2026-07-30 16:51:12.000000,2026-08-03 00:00:00,clalit,אורתופדיה,"ד""ר סמניסטי אלכסנדר","החשמונאים 1, טבריה",4.0,טבריה
3,2026-07-30 16:51:12.000000,2026-08-03 00:00:00,clalit,אורתופדיה,"ד""ר אבראהים נדיר",צפת,4.0,צפת
4,2026-07-30 16:51:12.000000,2026-08-03 00:00:00,clalit,אורתופדיה,"ד""ר קליימן מיכאל","מעלה חוני המעגל 12, חצור הגלילית",4.0,חצור הגלילית
...,...,...,...,...,...,...,...,...
13587,2026-07-31 11:16:39.116111,2026-09-30 08:24:00,maccabi,רפואת הפה,דר מור בר אילן,"שפיגל זוסיה 3, פתח תקווה",61.0,פתח תקווה
13588,2026-07-31 11:16:39.116111,2026-10-13 10:00:00,maccabi,רפואת הפה,דר מור בר אילן,"הנדיב 3, הרצליה",74.0,הרצליה
13589,2026-07-31 11:16:39.116111,2026-10-19 17:00:00,maccabi,רפואת הפה,דר אנה פיקובסקי,"שד רגר יצחק 53/2, באר שבע",80.0,באר שבע
13590,2026-07-31 11:16:39.116111,2027-01-06 09:00:00,maccabi,רפואת הפה,דר אסנת קורן,"ביל""ו 51 ג', רעננה",159.0,רעננה
13591,2026-07-31 11:16:39.116111,NaT,maccabi,רפואת הפה,דר רינת שוימר נוי,"הלל 14, ירושלים",NaN,ירושלים

In [43]:
data.drop(columns=["timestamp"]).drop_duplicates()

,available_date,kupah,profession,doctor_name,address,days_diff,city
0,2026-08-02 00:00:00,clalit,אורתופדיה,"ד""ר לוין מארק","שיאון, קצרין",3.0,קצרין
1,2026-08-02 00:00:00,clalit,אורתופדיה,"ד""ר מחאמיד חסן",מעלה עירון,3.0,מעלה עירון
2,2026-08-03 00:00:00,clalit,אורתופדיה,"ד""ר סמניסטי אלכסנדר","החשמונאים 1, טבריה",4.0,טבריה
3,2026-08-03 00:00:00,clalit,אורתופדיה,"ד""ר אבראהים נדיר",צפת,4.0,צפת
4,2026-08-03 00:00:00,clalit,אורתופדיה,"ד""ר קליימן מיכאל","מעלה חוני המעגל 12, חצור הגלילית",4.0,חצור הגלילית
...,...,...,...,...,...,...,...
13587,2026-09-30 08:24:00,maccabi,רפואת הפה,דר מור בר אילן,"שפיגל זוסיה 3, פתח תקווה",61.0,פתח תקווה
13588,2026-10-13 10:00:00,maccabi,רפואת הפה,דר מור בר אילן,"הנדיב 3, הרצליה",74.0,הרצליה
13589,2026-10-19 17:00:00,maccabi,רפואת הפה,דר אנה פיקובסקי,"שד רגר יצחק 53/2, באר שבע",80.0,באר שבע
13590,2027-01-06 09:00:00,maccabi,רפואת הפה,דר אסנת קורן,"ביל""ו 51 ג', רעננה",159.0,רעננה
13591,NaT,maccabi,רפואת הפה,דר רינת שוימר נוי,"הלל 14, ירושלים",NaN,ירושלים