In [1]:
# pip install geopy geopandas shapely

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
import prepare_data

In [5]:
data = prepare_data.open_and_clean_all(
    "data/raw/clalit/diaries.csv",
    "data/raw/maccabi/maccabi_full_data_with_appointments.json",
)

In [7]:
data.tail(5)

,timestamp,available_date,kupah,profession,doctor_name,address,days_diff,city
13965,2026-07-31 10:24:55.782577,2026-09-30 08:24:00,maccabi,רפואת הפה,דר מור בר אילן,"שפיגל זוסיה 3, פתח תקווה",61.0,פתח תקווה
13966,2026-07-31 10:24:55.782577,2026-10-13 10:00:00,maccabi,רפואת הפה,דר מור בר אילן,"הנדיב 3, הרצליה",74.0,הרצליה
13967,2026-07-31 10:24:55.782577,2026-10-19 17:00:00,maccabi,רפואת הפה,דר אנה פיקובסקי,"שד רגר יצחק 53/2, באר שבע",80.0,באר שבע
13968,2026-07-31 10:24:55.782577,2027-01-06 09:00:00,maccabi,רפואת הפה,דר אסנת קורן,"ביל""ו 51 ג', רעננה",159.0,רעננה
13969,2026-07-31 10:24:55.782577,NaT,maccabi,רפואת הפה,דר רינת שוימר נוי,"הלל 14, ירושלים",NaN,ירושלים

In [10]:
data.to_csv("data/clean/merged.csv", index=False)
data[data["kupah"] == "maccabi"].to_csv("data/clean/maccabi.csv", index=False)
data[data["kupah"] == "clalit"].to_csv("data/clean/clalit.csv", index=False)

In [9]:
data

,timestamp,available_date,kupah,profession,doctor_name,address,days_diff,city
0,2026-07-30 13:01:20.000000,2026-08-11 00:00:00,clalit,אורתופדיה,"ד""ר הלר אייל","דרך משה דיין 147, תל אביב יפו",12.0,תל אביב יפו
1,2026-07-30 13:01:20.000000,2026-08-14 00:00:00,clalit,אורתופדיה,"ד""ר צרפתי ירון","אליהו ברלין 13, תל אביב יפו",15.0,תל אביב יפו
2,2026-07-30 13:01:20.000000,2026-08-16 00:00:00,clalit,אורתופדיה,"ד""ר אשכול זאב","אבן גבירול 124, תל אביב יפו",17.0,תל אביב יפו
3,2026-07-30 13:01:20.000000,2026-08-16 00:00:00,clalit,אורתופדיה,"ד""ר סודיה דן","שדרות ישראל גורי 39, תל אביב יפו",17.0,תל אביב יפו
4,2026-07-30 13:01:20.000000,2026-08-17 00:00:00,clalit,אורתופדיה,"ד""ר לשינר ויאצ'סלב","שדרות יד לבנים 35, תל אביב יפו",18.0,תל אביב יפו
...,...,...,...,...,...,...,...,...
13965,2026-07-31 10:24:55.782577,2026-09-30 08:24:00,maccabi,רפואת הפה,דר מור בר אילן,"שפיגל זוסיה 3, פתח תקווה",61.0,פתח תקווה
13966,2026-07-31 10:24:55.782577,2026-10-13 10:00:00,maccabi,רפואת הפה,דר מור בר אילן,"הנדיב 3, הרצליה",74.0,הרצליה
13967,2026-07-31 10:24:55.782577,2026-10-19 17:00:00,maccabi,רפואת הפה,דר אנה פיקובסקי,"שד רגר יצחק 53/2, באר שבע",80.0,באר שבע
13968,2026-07-31 10:24:55.782577,2027-01-06 09:00:00,maccabi,רפואת הפה,דר אסנת קורן,"ביל""ו 51 ג', רעננה",159.0,רעננה
13969,2026-07-31 10:24:55.782577,NaT,maccabi,רפואת הפה,דר רינת שוימר נוי,"הלל 14, ירושלים",NaN,ירושלים